// cardsData.js
const cardsData = [
  { id: 1, title: "Laptop", description: "High performance laptop for everyday use.", image: "https://picsum.photos/seed/laptop/400/300" },
  { id: 2, title: "Headphones", description: "Noise cancelling over-ear headphones.", image: "https://picsum.photos/seed/headphones/400/300" },
  { id: 3, title: "Smartphone", description: "Latest generation smartphone with powerful features.", image: "https://picsum.photos/seed/smartphone/400/300" },
  { id: 4, title: "Watch", description: "Stylish smartwatch with fitness tracking.", image: "https://picsum.photos/seed/watch/400/300" },
  { id: 5, title: "Camera", description: "DSLR camera for professional photography.", image: "https://picsum.photos/seed/camera/400/300" },
  { id: 6, title: "Shoes", description: "Comfortable and trendy running shoes.", image: "https://picsum.photos/seed/shoes/400/300" },
  { id: 7, title: "Backpack", description: "Durable backpack for travel and daily use.", image: "https://picsum.photos/seed/backpack/400/300" },
  { id: 8, title: "Sunglasses", description: "UV protection stylish sunglasses.", image: "https://picsum.photos/seed/sunglasses/400/300" },
  { id: 9, title: "Keyboard", description: "Mechanical keyboard for fast typing.", image: "https://picsum.photos/seed/keyboard/400/300" },
  { id: 10, title: "Mouse", description: "Wireless mouse with ergonomic design.", image: "https://picsum.photos/seed/mouse/400/300" },
  { id: 11, title: "Gaming Console", description: "Next-gen gaming console for unlimited fun.", image: "https://picsum.photos/seed/gamingconsole/400/300" },
  { id: 12, title: "TV", description: "Smart LED TV with 4K resolution.", image: "https://picsum.photos/seed/tv/400/300" },
  { id: 13, title: "Tablet", description: "Portable tablet with large display.", image: "https://picsum.photos/seed/tablet/400/300" },
  { id: 14, title: "Speaker", description: "Bluetooth speaker with deep bass.", image: "https://picsum.photos/seed/speaker/400/300" },
  { id: 15, title: "Drone", description: "High-tech drone with 4K camera.", image: "https://picsum.photos/seed/drone/400/300" },
  { id: 16, title: "Perfume", description: "Luxury perfume with long-lasting fragrance.", image: "https://picsum.photos/seed/perfume/400/300" },
  { id: 17, title: "Jacket", description: "Warm and comfortable winter jacket.", image: "https://picsum.photos/seed/jacket/400/300" },
  { id: 18, title: "Cap", description: "Cool baseball cap for everyday wear.", image: "https://picsum.photos/seed/cap/400/300" },
  { id: 19, title: "Wallet", description: "Leather wallet with multiple compartments.", image: "https://picsum.photos/seed/wallet/400/300" },
  { id: 20, title: "Chair", description: "Ergonomic office chair for comfort.", image: "https://picsum.photos/seed/chair/400/300" },
  { id: 21, title: "Desk", description: "Modern wooden study desk.", image: "https://picsum.photos/seed/desk/400/300" },
  { id: 22, title: "Lamp", description: "Stylish desk lamp for study or work.", image: "https://picsum.photos/seed/lamp/400/300" },
  { id: 23, title: "Bottle", description: "Reusable water bottle for daily use.", image: "https://picsum.photos/seed/bottle/400/300" },
  { id: 24, title: "Fan", description: "Electric fan with three speed settings.", image: "https://picsum.photos/seed/fan/400/300" },
  { id: 25, title: "Microwave", description: "Compact microwave oven for your kitchen.", image: "https://picsum.photos/seed/microwave/400/300" },
  { id: 26, title: "Fridge", description: "Energy efficient double door fridge.", image: "https://picsum.photos/seed/fridge/400/300" },
  { id: 27, title: "Washing Machine", description: "Automatic washing machine with smart wash.", image: "https://picsum.photos/seed/washingmachine/400/300" },
  { id: 28, title: "Oven", description: "Electric oven for baking and grilling.", image: "https://picsum.photos/seed/oven/400/300" },
  { id: 29, title: "Iron", description: "Electric iron with steam function.", image: "https://picsum.photos/seed/iron/400/300" },
  { id: 30, title: "Blender", description: "High-speed blender for smoothies and juices.", image: "https://picsum.photos/seed/blender/400/300" },
];

export default cardsData;
